# Generated by Django 5.0.6 on 2024-12-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('type', models.CharField(max_length=50, verbose_name='Вид питомца')),
                ('gender', models.CharField(max_length=6, verbose_name='Пол')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('color', models.CharField(max_length=50, verbose_name='Масть')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_birth_approx', models.BooleanField(default=False, verbose_name='Примерная дата рождения да/нет')),
                ('breeding_data', models.BooleanField(default=False, verbose_name='Племенные данные')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('owners', models.ManyToManyField(blank=True, related_name='pets', to='users.ownerprofile')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ('name',),
                'default_related_name': 'pets',
            },
        ),
        migrations.CreateModel(
            name='PetMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHIP', 'Чип'), ('TAG', 'Бирка'), ('STAMP', 'Клеймо')], max_length=5, verbose_name='Тип маркировки')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер маркировки')),
                ('is_verifed', models.BooleanField(default=False, verbose_name='Верифицирован да/нет')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Маркировка питомца',
                'verbose_name_plural': 'Маркировки питомцев',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='Юридическое лицо')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('document_series_number', models.CharField(max_length=50, verbose_name='Серия и номер документа')),
                ('document_issuance_date', models.DateField(verbose_name='Дата выдачи документа')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owners', to='pets.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото питомца')),
                ('main_photo', models.BooleanField(default=False, verbose_name='Главное фото да/нет')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type_treatment', models.CharField(max_length=100, verbose_name='Тип обработки')),
                ('medicament', models.CharField(max_length=100, verbose_name='Медикамент')),
                ('date_treatment', models.DateField(verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Обработка',
                'verbose_name_plural': 'Обработки',
                'ordering': ('date_treatment',),
                'default_related_name': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип вакцинации')),
                ('medicament', models.CharField(max_length=100, verbose_name='Медикамент')),
                ('date_vaccination', models.DateField(verbose_name='Дата вакцинации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
                'ordering': ('date_vaccination',),
                'default_related_name': 'vaccinations',
            },
        ),
        migrations.AddConstraint(
            model_name='petmarking',
            constraint=models.UniqueConstraint(fields=('pet', 'type'), name='unique_pet_type'),
        ),
        migrations.AddConstraint(
            model_name='petphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('main_photo', True)), fields=('pet',), name='unique_main_photo_per_pet'),
        ),
    ]
