# Generated by Django 5.0.6 on 2024-12-20 09:53

import apps.users.models
import apps.users.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('email_is_hidden', models.BooleanField(default=False, verbose_name='Скрыть почту')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[apps.users.utils.PhoneValidator()], verbose_name='Телефон')),
                ('phone_is_hidden', models.BooleanField(default=False, verbose_name='Скрыть телефон')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=255, validators=[apps.users.utils.FirstNameValidator], verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, validators=[apps.users.utils.LastNameValidator], verbose_name='Фамилия')),
                ('date_birth', models.DateField(blank=True, null=True, validators=[apps.users.utils.BirthValidator], verbose_name='День рождения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('is_curator', models.BooleanField(default=False, verbose_name='Куратор')),
                ('about_me_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок описания')),
                ('about_me_text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Модератор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.users.models.ZooUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('passport', models.ImageField(upload_to=apps.users.utils.curator_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Паспорт')),
                ('contract', models.FileField(upload_to=apps.users.utils.curator_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'odt', 'sxg'])], verbose_name='Контракт')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Проведена проверка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='Владелец - юридическое лицо')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('document_series_number', models.CharField(max_length=50, verbose_name='Серия и номер документа')),
                ('document_issuance_date', models.DateField(verbose_name='Дата выдачи документа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
